base: &base
  adapter: postgresql
  host: localhost
  username: postgres

development:
  <<: *base

test:
  <<: *base

production:
  <<: *base
  host: database

build:
  adapter: sqlite3
  database: db/build.sqlite3
