version: '3'
volumes:
  logs:
services:
  database:
    image: postgres:9.6.2
  shop:
    build:
      context: shop
    depends_on:
      - database
    volumes:
      - logs:/log
    ports:
      - 3000:3000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      - xpack.security.enabled=false
  logstash:
    build:
      context: logstash
    depends_on:
      - elasticsearch
    volumes:
      - logs:/log
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    environment:
      XPACK_SECURITY_ENABLED: 'false'
    ports:
      - 5601:5601
